In [7]:
'''
Consider the below code to answer further questions:
import numpy as np
list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]
array_list = np.array(object = list_)
Que-1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

Ans- Yes there is difference in data type of list_ and array_list 
     'list_', it is type of list which is containing str value.
     'array_list' it is type of array 
'''

In [16]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

In [18]:
type(list_)

list

In [19]:
type(array_list)

numpy.ndarray

In [21]:
'''
Que-2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.

Ans - 
'''
list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)
# print the data type of each element in list_
for item in list_:
    print(type(item))

# print the data type of each element in array_list
for item in array_list:
    print(type(item))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [ ]:
'''
Que-3. Considering the following changes in the variable, array_list:
       array_list = np.array(object = list_, dtype = int) 
'''

In [26]:
array_list = np.array(object = list_, dtype = int)

In [27]:
array_list

array([1, 2, 3, 4, 5])

In [28]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_, dtype=int)

# Print data types of elements in list_
print("Data types of elements in list_:")
for item in list_:
    print(type(item))

print("\n")

# Print data types of elements in array_list
print("Data types of elements in array_list:")
for item in array_list:
    print(type(item))


Data types of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


Data types of elements in array_list:
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>


In [29]:
'''
Consider the below code to answer further questions:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)
Que-4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size
'''
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [30]:
num_array.shape

(2, 3)

In [31]:
num_array.size

6

In [38]:
'''
Que-5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]
'''
arr1=np.zeros((3,3))

In [39]:
arr1

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [40]:
arr1.shape

(3, 3)

In [51]:
'''
Que-6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]
'''
identArr = np.identity((5))  # or np.diag(np.ones(5))

In [52]:
identArr

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])